Repository atomist/sdm-pack-spring, pull requests merged in 2018-08, with the labels that each got.

#19 Fix arguments to support Spring Boot 2
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
  lib/spring/deploy/localSpringBootDeployers.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#20 Add command to list branch deploys
  index.ts
  legal/THIRD_PARTY.md
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
Labels: changelog:added

#22 Goal is now dependent on BuildGoal
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#31 Remove obsolete code and update to latest SDM
  README.md
  index.ts
  lib/java/generate/JavaGeneratorConfig.ts
  lib/java/generate/generatorConfig.ts
  lib/maven/pushTests.ts
  lib/maven/review/providedDependencyReviewer.ts
  lib/spring.ts
  lib/spring/pushTests.ts
  lib/spring/review/hardcodedPropertyReviewer.ts
  lib/spring/springConstants.ts
  package-lock.json
  package.json
  test/java/review/fileIoImportReviewer.test.ts
  test/java/review/importDotStarReviewer.test.ts
  test/maven/review/providedDependencyReviewer.test.ts
  test/spring/review/hardCodedPropertyReviewer.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve
