Repository atomist/sdm-pack-spring, pull requests merged in 2018-09, with the labels that each got.

#36 Update to latest SDM
  lib/spring.ts
  lib/spring/generate/springBootTransforms.ts
  lib/spring/generate/transformSeedToCustomProject.ts
  package-lock.json
  package.json
  test/java/transform/updatePom.test.ts
  test/spring/generator/SpringBootProjectStructure.test.ts
  test/spring/generator/springBootTransforms.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#41 Add user agent to Spring Initializr call
  lib/spring/generate/springInitializrGenerator.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#43 Use start.spring.io metadata in order to validate input parameters
  lib/spring/generate/springInitializrGenerator.ts
  package-lock.json
Labels: auto-merge-method:squash, auto-merge:on-approve

#45 Add Maven goal preparations and version helpers
  index.ts
  lib/maven/build/MavenBuilder.ts
  lib/maven/build/helpers.ts
  package-lock.json
  package.json
  test/maven/fingerprint/mavenFingerprint.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#51 Use cross-spawn
  lib/gradle/build/GradleSingleModuleBuilder.ts
  lib/gradle/deploy/GradlePerBranchSpringBootDeploymentGoal.ts
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
  lib/java/deploy/executableJarDeployer.ts
  lib/maven/build/MavenBuilder.ts
  lib/maven/build/helpers.ts
  lib/maven/deploy/mavenDeployer.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:fixed

#63 Use 127.0.0.1 in local URLs
  lib/gradle/deploy/GradlePerBranchSpringBootDeploymentGoal.ts
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
  lib/spring/deploy/localSpringBootDeployers.ts
Labels: auto-merge:on-approve, changelog:changed

#64 Only use mvnw on win32 if JAVA_HOME set
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
  lib/maven/build/MavenBuilder.ts
  lib/maven/build/helpers.ts
  lib/maven/deploy/mavenDeployer.ts
  lib/maven/mavenCommand.ts
  test/maven/MavenCommand.test.ts
Labels: auto-merge:on-approve, changelog:fixed

#66 Use string replacement for package
  index.ts
  lib/java/transform/bringInFile.ts
  lib/spring/transform/guide/securingWebApp.ts
  package-lock.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#67 Transform and autofix to add Spring Actuator to the project
  index.ts
  lib/spring/transform/addSpringBootActuator.ts
  lib/spring/transform/guide/securingWebApp.ts
  test/spring/transform/addSpringBootActuator.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#81 Add ReviewListeners for cloud native and spring style
  index.ts
  lib/spring.ts
  lib/spring/review/findNonSpecificMvcAnnotations.ts
  lib/spring/review/hardcodedPropertyReviewer.ts
  lib/spring/review/mutableInjectionsReviewer.ts
  lib/spring/transform/removeUnnecessaryComponentScanAnnotations.ts
  package-lock.json
  package.json
  test/spring/review/hardCodedPropertyReviewer.test.ts
Labels: auto-merge:on-approve
