Repository atomist/sdm-pack-spring, pull requests merged in 2019-04, with the labels that each got.

#130 Added extended Gradle support
  .atomist/hooks/pre-code-build
  index.ts
  lib/gradle/build/GradleSingleModuleBuilder.ts
  lib/gradle/build/gradleBuilder.ts
  lib/gradle/build/gradleLogInterpreter.ts
  lib/gradle/build/helpers.ts
  lib/gradle/parse/buildGradleParser.ts
  lib/gradle/pushtest/gradlePushTests.ts
  lib/gradle/review/hasGradleVersion.ts
  lib/spring/pushtest/pushTests.ts
  lib/spring/review/hardcodedPropertyReviewer.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:added

#136 Fixes gradle builds for Spring Initializr
  index.ts
  lib/gradle/build/gradleBuilder.ts
  lib/gradle/build/helpers.ts
  lib/gradle/deploy/GradlePerBranchSpringBootDeploymentGoal.ts
  lib/gradle/parse/buildGradleParser.ts
  lib/gradle/review/hasGradleVersion.ts
  lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts
  lib/maven/build/helpers.ts
  lib/maven/inspection/findDependencies.ts
  lib/spring/generate/springBootTransforms.ts
  lib/spring/generate/springInitializrGenerator.ts
  lib/spring/generate/transformSeedToCustomProject.ts
  test/gradle/parse/buildGradleParser.test.ts
  test/spring/generator/springBootTransforms.test.ts
Labels: auto-merge:on-approve

#139 Allow to pass Maven CLI options and properties
  lib/maven/build/MavenBuilder.ts
  lib/maven/build/helpers.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement
